version: 2.1

orbs:
  windows: circleci/windows@2.4.0

jobs:
  build:
    working_directory: ~/repo
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  build-deploy:
    working_directory: ~/repo
    executor:
      name: windows/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d6:f7:45:72:3c:da:b0:df:55:58:d3:00:05:57:93:f1"
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Check IP Address current Circleci Instance
          command: .\.circleci\ipAddress.ps1
      - run:
          name: Install POSH-SSH
          command: .\.circleci\install_posh_ssh.ps1
      - run:
          name: Update Host
          command: .\.circleci\set_known_hosts.ps1
      - run:
          name: Deploy App into EC2
          command: .\.circleci\ssh_deploy.ps1
      - run:
          name: Remove Ip from EC2 and Delete Aws Credentials 
          command: .\.circleci\removeIpAddress.ps1
          when: always

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-deploy:
          filters:
            branches:
              only:
                - circleci

  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci