version: 2.1

orbs:
  windows: circleci/windows@2.4.0

jobs:
  build:
    working_directory: ~/repo
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  build-deploy:
    working_directory: ~/repo
    executor:
      name: windows/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "88:fd:6a:c9:68:18:ff:7e:5b:41:29:c4:5d:32:94:b4"
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Install Transfertto
          command: .\.circleci\install_transfertto.ps1
      - run:
          name: Update Host
          command: .\.circleci\Set_Known_Hosts.ps1
      - run:
          name: Deploy App into EC2
          shell: bash.exe
          command: ./.circleci/GIT_Bash_Setup.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-deploy:
          filters:
            branches:
              only:
                - circleci

  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci